export const eventTypes = [
  {
    label: "Workshops",
    value: "workshops",
    color: "bg-green-500",
    border: "border-green-500",
    bg: "bg-green-100",
    fill: "fill-green-500",
    stroke: "stroke-green-500",
  },
  {
    label: "Meeting",
    value: "meeting",
    color: "bg-blue-500",
    border: "border-blue-500",
    bg: "bg-blue-100",
    fill: "fill-blue-500",
    stroke: "stroke-blue-500",
  },
  {
    label: "Donation",
    value: "donation",
    color: "bg-orange-500",
    border: "border-orange-500",
    bg: "bg-orange-100",
    fill: "fill-orange-500",
    stroke: "stroke-orange-500",
  },
  {
    label: "Training",
    value: "training",
    color: "bg-violet-500",
    border: "border-violet-500",
    bg: "bg-violet-100",
    fill: "fill-violet-500",
    stroke: "stroke-violet-500",
  },
  {
    label: "Awareness Session",
    value: "awareness-session",
    color: "bg-teal-500",
    border: "border-teal-500",
    bg: "bg-teal-50",
    fill: "fill-teal-500",
    stroke: "stroke-teal-500",
  },
];
